## docker-compose
version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    #command: python manage.py runserver 0.0.0.0:8000
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ".:/code:cached"
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
    driver: local